### PR TITLE
cue: add a test case for `list.Equals`

### PR DESCRIPTION
**Pull request by adieu**
Found this case when debugging the failed test for #200 

It's failing because of https://github.com/cuelang/cue/commit/52b04d409b31e439704de4884388840fec6e2dc7#diff-104bcbf8410c0cd325212e1b0af431aeL90

### CODE REVIEW

**Comment by mpvl** [comment]
I think the most attainable fix here is the following: 
- Let Equals ignore optional fields (operate on the manifested value)
- Document the behavior or Equals to be structural for non-concrete values.

In general, as noted in #200, determining equality of incomplete structs is a dubious endeavor.

I hope to fix this today.

**Comment by mpvl** [comment]
You can rebase and rerun the tests. Should work now.

**Comment by adieu** [comment]
Rebased. I've run the tests locally and all passed.

**Comment by adieu** [comment]
I'm not sure if this test case is still needed any longer as more tests had been added in recent commits. Feel free to close it if it's not needed.

**Comment by mpvl** [comment]
I deliberately did not add the test case to types_test.go so this could go in. :)

**Pull request closed without merging**
