### PR TITLE
Implement Custom Command flags

### PR DESCRIPTION
**Pull request by leejansq**
Implement Custom Command flags. generate and parse custom flags

### CODE REVIEW

**Comment by mpvl** [comment]
This is missing tests, documentation. I'm not entire sure what this is supposed to do.

Also, this seems to overlap with `--inject` flag. How does this compare and do we need both?

Thanks!

**Comment by leejansq** [comment]
following the  tutorial, the demo did not work
```
 package foo

        import "tool/exec"

        city: "Amsterdam"

        // Say hello!
        command: hello: {
                // whom to say hello to
                var: who: *"World" | string

                task: print: exec.Run & {
                        cmd: "echo Hello \(var.who)! Welcome to \(city)."
                }
        }

```
cue cmd print test.io/foo --who=cue
then, produce an error
```
cannot find package "--who=cue"
```
I think the feature is TODO. 
This is what the PR is supposed to do

**Comment by verdverm** [comment]
@leejansq try running `cue help injection` on the latest master. This is a newer feature that likely solves this issue more generally.

**Comment by mpvl** [comment]
@leejansq thanks for the explanation. That tutorial is indeed incorrect. I've found the relevant documentation and will fix it.

I'm curious to know if you run into any limitations with the --injection feature.

Thanks!

**Comment by leejansq** [comment]
@mpvl @verdverm  thanks， Although the --injection feature can solve the problem, but I still feel the two are different

1. The purpose of  "cue cmd" command is to run a user-defined shell command
So In this case, i think users  should be allowed to customize subcommand flags

2. --injection feature and user-defined  subcommand flags have different scope，just like tool file 
 and subcommand
 for example, different user-defined  subcommand can have the same flags

**Comment by verdverm** [comment]
linking to #337

**Comment by verdverm** [comment]
On thing to note is that Cue does not evaluate attributes as part of the unification process. That is, they have no impact on decision making, aren't type / error checked, and largely are processed as strings and carried around to support future tool development.

I do agree the UX/DX is a little off for `cue cmd`. The -t flag positioning is a little strict and args are hard. I think there is something where we use the `--` to separate cue's normal flags / args and everything after. We could make some assumptions around the most common invocation formats (likely `cue cmd <name> ... flags and args intended for the scripted command. In this way, most cases would not require the `--` for separation. The main issue here is the **cobra** library, flag processing, and supporting both Cue's shared flags / args via cobra and the custom flags / args in `cue cmd`. Fortunately, the way the cobra commands are constructed (i.e. `cmd` is a special case and cue handles the cobra root command in a custom way to support Cue's fallback to cmd when the first subcmd is in the scripting layer (i.e. we can write code and docs so that `cue deploy` or `cue whatever` are possible))

**Comment by myitcv** [comment]
Hi @leejansq - thanks for creating this PR. 

CUE recently moved to a new organisation on GitHub: https://github.com/cue-lang/cue/issues/1078. Unfortunately we were unable to transfer this repository to the new organisation, and so pull requests will need to be re-created at https://github.com/cue-lang/cuelang.org.

Apologies for the inconvenience - we look forward to seeing you in CUE's new home. 

Thank you again for contributing to the CUE project!

**Pull request closed without merging**
