### PR TITLE
Move from apps/v1beta1 to apps/v1 for Kubernetes tutorial

### PR DESCRIPTION
**Pull request by metalmatze**
StatefulSets and Deployments are apps/v1 now and v1beta1 is soon deprecated.

Not 100% if this is correct. How do I run `cue generate`?

### CODE REVIEW

**Comment by jlongtine** [comment]
@metalmatze `cue generate` isn't a `cue` command currently. What are you trying to generate? The kubernetes CUE definitions?

**Comment by metalmatze** [comment]
Yes, exactly. We should update those ApiVersion for Deployment and StatefulSet as they are deprecated and removed with Kubernetes 1.16 (AFAIK).
Therefore I've updated all instances of those ApiVersions, however it would be great to actually generated the YAML things too and not only change them by hand.

**Comment by jlongtine** [comment]
@metalmatze This [line](https://github.com/cuelang/cue/pull/54/files#diff-36dd22f9a02f8b3c51641d53bb2c3c6dR1042) (`cue get go k8s.io/api/apps/v1`) grabs the kubernetes source, go through it, and generates the CUE definitions for `apps/v1`. If you run that command in `doc/tutorial/kubernetes/quick`, it will generate the definitions you're looking for.

**Comment by mpvl** [comment]
Sorry for the late chime in. To update the test files one can run `go test -update`. This should not be part of the usual `go generate` step, which is run often as part of the test.

The files in .../kubernetes/testdata are the source of truth. The files in quick are all generated (I know, a bit opposite), with the exception that files in other testdata directories are also generated.

**Comment by mpvl** [comment]
See https://cue-review.googlesource.com/c/cue/+/4205

**Pull request closed without merging**
