### PR TITLE
[Draft] Implement gen go command

### PR DESCRIPTION
**Pull request by offlinehacker**
This is initial attempt to implement `cue gen go` command.

### CODE REVIEW

**Comment by offlinehacker** [comment]
@googlebot I signed it!

**Comment by offlinehacker** [comment]
@mpvl do you think this is implemented in the right direction, or were you planning to do different interface? I needed this command, so i can use cue to embed it into my own project, but i would like to contribute back.

**Comment by mpvl** [comment]
@offlinehacker: the general approach is good. It is mostly naming that is an issue. I long had exactly the same idea for naming. However, the name `gen` is a bit problematic, as it turns out:

1.  I intend to add a `generate` command analogous to the `go generate` command at some point, and the existence of the two will be confusing.
2. It turns out that the distinction between `import`/`export` for data and `get`/`gen` for schema in addition to having `eval` and all is a bit confusing. There are a lot of options and the boundary between the two is not always that clear.

So the plan is to have `import` and `export` only for importing and "generating" (`get` may even be deprecated), in other words converting between namesake files. `cue <files>`, so without a command, would replace `eval` as well as `import` and `export` for single-file creation. This format also fits more naturally with using `cue` for quick queries on existing data. Note that this would change the meaning of `export`, so perhaps that should get a different name.

In the Go generation case. `cue export -out go <pkgs>`, or something like that, would be used to generate namesake files to existing `.cue` files, whereas `cue <pkg> -o foo.go` could be used to generate Go into a single file. In the latter case, the extension indicates the desired format is Go.
The idea is to have further qualifiers to indicate what should be generated (e.g. `-o foo.go:struct` or `-o struct:foo.go` to export only structs definitions to the file `foo.go`).

**Anyway, to be compatible with these future changes, you could hook your implementation into the `--out` flag of you the `export` command.**

**Comment by myitcv** [comment]
Hi @offlinehacker - thanks for creating this PR. 

CUE recently moved to a new organisation on GitHub: https://github.com/cue-lang/cue/issues/1078. Unfortunately we were unable to transfer this repository to the new organisation, and so pull requests will need to be re-created at https://github.com/cue-lang/cuelang.org.

Apologies for the inconvenience - we look forward to seeing you in CUE's new home. 

Thank you again for contributing to the CUE project!

**Pull request closed without merging**
