### PR TITLE
doc/tutorial/: Update import label format.

### PR DESCRIPTION
**Pull request by phaer**
Fixes an inline mentioned  to-do: `<-- TODO: update import label format -->`.

### CODE REVIEW

**Comment by phaer** [comment]
@googlebot I signed it!

**Comment by mpvl** [comment]
The format has changed for the next release as part of a big cli-tool overhaul.
As the Kubernetes documentation on cuelang.org is automatically synced to the latest version (should be a copy of a specific version), it may be out of sync.

The correct fix would be to copy over the kubernetes docs in the build script in cuelang.org.

**Comment by mpvl** [comment]
Note that the examples in the docs are run through a simulator, which is why these tests are failing.

**Comment by mpvl** [comment]
This should be fixed as of v0.1.0. Sorry about the confusion!

Paul has also fixed the documentation infra so that we can have different versions for tip. Now all that remains is porting the k8s tutorial to cuelang.org.

**Pull request closed without merging**
